### ISSUE TITLE
Example test case with commit IDs (Before, Regression, Fix) for a data.table-specific test

### ISSUE THREAD

**Issue by Anirban166** [tdhock/atime#31]
There are currently two types of tests that I see for cases you would put in a repository's `inst/atime/tests.R` file: (and in our case the repository is a fork of `data.table` here)
A) Test case not having any commit SHA/IDs ([example](https://github.com/DorisAmoakohene/data.table/blob/master/inst/atime/tests.R))
B) Test case having the three commit IDs ([example](https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table/blob/main/groupby%20with%20dogroups%20(R%20expression)%20performance%20regression%20%234200.Rmd))

@DorisAmoakohene said that she couldn't run test cases of type (B) with Siyao's GitHub Action when she tested earlier. In other words, only the `test.list` version without the IDs (A) worked for her when she tested it with Siyao's GitHub Action, and that's why she removed the commit IDs in her fork of `data.table` (correct me if I'm wrong Doris).

So can you provide a concrete example/code of a test to include within `test.list` that includes commit IDs? (and again this is for `data.table`)

**Comment by tdhock** [comment]
please read the man page of atime_pkg. It says that each element of test.list should be an argument which is passed to atime_versions. so some of these can be versions like type B.
This example should work https://github.com/DorisAmoakohene/data.table/blob/master/inst/atime/tests.R but quote in N in not necessary, and the 3 versions should be added.

**Comment by tdhock** [comment]
(if it doesn't work with the versions for some reason, please file an issue with details so we can fix it, instead of removing the versions)

**Comment by Anirban166** [comment]
> It says that each element of test.list should be an argument which is passed to atime_versions. so some of these can be versions like type B.

Makes sense, so in essence it's like you're passing everything that is an argument to `atime_pkg` to `atime_versions` under the hood (with something like an ellipsis notation I reckon)

The man page of `atime_versions` did help, or to see this argument stated more specifically:
> sha.vec | named character vector / list of SHA commit IDs.

I got it to work and now I can see the labels of 'Before', 'Regression', and 'Fix' on my plots :)

> This example should work https://github.com/DorisAmoakohene/data.table/blob/master/inst/atime/tests.R but quote in N in not necessary, and the 3 versions should be added.

Do you have the three versions/commits for that example?

**Comment by tdhock** [comment]
> Makes sense, so in essence it's like you're passing everything that is an argument to `atime_pkg` to `atime_versions` under the hood (with something like an ellipsis notation I reckon)

Actually there should be only one argument to `atime_pkg("path/to/package_repo_clone")`
The elements of `test.list` are passed to `atime_versions`

> Do you have the three versions/commits for that example?

@DorisAmoakohene should have them in her work repo https://github.com/DorisAmoakohene/Efficiency-and-Performance-Test.RData.table please file an issue there and ask her to update/organize if you are not able to find the info.
