### ISSUE TITLE
Expose a way to control faceting of many tests

### ISSUE THREAD

**Issue by MichaelChirico** [tdhock/atime#49]
https://github.com/tdhock/atime/blob/1dac9ef8056a751095f88264aad24d7ed30aa851/R/versions.R#L296

As noted (https://github.com/Rdatatable/data.table/pull/6094), the plot displayed will become very wide / unsuitable for a GitHub comment as the number of expressions increases.

What's the most natural way for the user to hint to atime the ideal shape for the output? e.g. giving a max of 3 columns of plots...

**Comment by tdhock** [comment]
can you please clarify why you think  a very wide plot would be unsuitable for a github comment? 
On my web browser, looking at the PR web page, yes the image is scaled to fit in the comment box, so too small to read.
But if you click on the plot image, it goes full screen in the browser, so easy to scroll through all of them, and in my opinion this should be suitable for checking all performance tests prior to merging a PR.
My design was that users can write their own plotting scripts, if they don't like the default. The atime_pkg function saves a tests.RData file, with all the test result numbers, so users can write a script to read in those data, and then do whatever they want. Does that seem reasonable for what you have in mind?
About letting the user specify the plot layout, such as max 3 columns, that would not work with facet_grid (if we want to keep data size N on X axis), but maybe could work with facet_wrap. But I am hesitant to define some option like that, and instead I would suggest if you have another plot in mind, please try to write an R script that can read the tests.RData and then output an alternative plot.png file.

**Comment by MichaelChirico** [comment]
OK SG! If this is not documented yet, I would recommend summarizing the above "in the right place" to close this issue. In data.table, we'll revisit later when the tests are more scaled up. Thanks!

**Comment by tdhock** [comment]
ok documented on ?atime_pkg https://github.com/tdhock/atime/commit/fe312cbebc6de79bc46dc743a038fcaab8e71957
