### ISSUE TITLE
Add an option to filter time/memory instead of plotting both units as a must always?

### ISSUE THREAD

**Issue by Anirban166** [tdhock/atime#53]
@tdhock what do you think about introducing such an option? (with reference to the title of this PR)

@DorisAmoakohene please check the steps I followed below for #52 

I got my hack to work, which is just a simple modification to the plot method to filter out the time measurements/data:
```r
plot.atime <- function(x, ...){
  expr.name <- N <- kilobytes <- NULL
  ## Above to avoid CRAN NOTE.
  meas <- x[["measurements"]]
  if(requireNamespace("ggplot2")) {
    tall.list <- list()
    for(unit.i in seq_along(x$unit.col.vec)) {
      col.name <- x$unit.col.vec[[unit.i]]
      unit <- names(x$unit.col.vec)[[unit.i]]
      if(unit %in% c("seconds")) {  # Selecting only the time unit.
        tall.list[[unit.i]] <- meas[, data.table(
          N, expr.name, unit, median=get(col.name))]
      }
    }
    tall <- rbindlist(tall.list)
    gg <- ggplot2::ggplot()+
      ggplot2::theme_bw()+
      ggplot2::geom_ribbon(ggplot2::aes(
        N, ymin=min, ymax=max, fill=expr.name),
        data=data.table(meas, unit="seconds"),
        alpha=0.5)+
      ggplot2::geom_line(ggplot2::aes(
        N, median, color=expr.name),
        data=tall)+
      ggplot2::facet_grid(unit ~ ., scales="free")+
      ggplot2::scale_x_log10(
        breaks=meas[, 10^seq(
          ceiling(min(log10(N))),
          floor(max(log10(N))))],
        limits=c(NA, meas[, max(N)*(max(N)/min(N))^0.5]))+
      ggplot2::scale_y_log10("median line, min/max band")
    if (requireNamespace("directlabels")) {
      gg <- directlabels::direct.label(gg, "right.polygons")
    }
    gg
  } else {
    lattice::xyplot(
      log10(median) ~ log10(N), meas,
      groups=expr.name, type="l",
      ylab="log10(median seconds)",
      auto.key=list(space="right", points=FALSE, lines=TRUE))
  }
}
```
So you can replace lines [201](https://github.com/tdhock/atime/blob/27bc2530bc86484996cbab365d50bd742e96b532/R/atime.R#L201) to [243](https://github.com/tdhock/atime/blob/27bc2530bc86484996cbab365d50bd742e96b532/R/atime.R#L243) of the `atime/R/atime.R` file in the `atime` library that you're loading in your system to the code snippet above. If you're not sure where your installation directory is located, you can use something like `print(system.file(package = "atime"))` to figure out where it is. 

If you're cloning `atime`, you can also remove that setup in the default location using `remove.packages("atime")` (also if you loaded it, might need to detach it using `detach("package:atime", unload = TRUE)` to avoid a corrupted `atime.rdb` database on lazy-loading) and then install it from the cloned directory by using `devtools::install(".")`. That's basically what I did.

Then run the example you want. For instance, I ran [this one](https://github.com/DorisAmoakohene/PerformanceTest_data.table/blob/8adaa363642ef13e95fc3b0ae5e23669aaf7989e/Working%20Examples/PR%205427/setDT%20extremely%20slow%20for%20very%20wide%20input%20%235426%20-%20Copy.Rmd#L32):
```r
library(atime)
library(ggplot2)
library(data.table)

tdir <- tempfile()
dir.create(tdir)
git2r::clone("https://github.com/Rdatatable/data.table", tdir)

atime.list.5427 <- atime::atime_versions(
  pkg.path=tdir,
  pkg.edit.fun=function(old.Package, new.Package, sha, new.pkg.path){
    pkg_find_replace <- function(glob, FIND, REPLACE){
      atime::glob_find_replace(file.path(new.pkg.path, glob), FIND, REPLACE)
    }
    Package_regex <- gsub(".", "_?", old.Package, fixed=TRUE)
    Package_ <- gsub(".", "_", old.Package, fixed=TRUE)
    new.Package_ <- paste0(Package_, "_", sha)
    pkg_find_replace(
      "DESCRIPTION", 
      paste0("Package:\\s+", old.Package),
      paste("Package:", new.Package))
    pkg_find_replace(
      file.path("src","Makevars.*in"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      Package_regex,
      new.Package_)
    pkg_find_replace(
      file.path("R", "onLoad.R"),
      sprintf('packageVersion\\("%s"\\)', old.Package),
      sprintf('packageVersion\\("%s"\\)', new.Package))
    pkg_find_replace(
      file.path("src", "init.c"),
      paste0("R_init_", Package_regex),
      paste0("R_init_", gsub("[.]", "_", new.Package_)))
    pkg_find_replace(
      "NAMESPACE",
      sprintf('useDynLib\\("?%s"?', Package_regex),
      paste0('useDynLib(', new.Package_))
  },
  N=10^seq(1,7),
  setup={ 
    DT = replicate(N, 1, simplify = FALSE)
  },
  expr=data.table:::setDT(DT),
  "slow"= "c4a2085e35689a108d67dacb2f8261e4964d7e12", #Parent of the first commit in the PR that fixes the issue(https://github.com/Rdatatable/data.table/commit/7cc4da4c1c8e568f655ab5167922dcdb75953801),
  "Fast"="1872f473b20fdcddc5c1b35d79fe9229cd9a1d15")#last commit in the PR that fixes the issue (https://github.com/Rdatatable/data.table/pull/5427/commits)
plot(atime.list.5427)+
  labs(title = "setDT extremely slow for very wide input #5426")

png("atime.list.5427.png", res = 600, width = 13, height = 8, unit = "in")
plot(atime.list.5427)+
  labs(title = "setDT extremely slow for very wide input #5426")+
  theme( plot.title = element_text(size = 30))
dev.off()
```

<img width="990" alt="image" src="https://github.com/tdhock/atime/assets/30123691/78045dc7-ebaf-4b1a-87ef-c0d4057416ac">

**Comment by DorisAmoakohene** [comment]
Thanks @Anirban166, my issue was how to get the base, CRAN and head on the graph, as @tdhock expect, for this I have a similar graph.

**Comment by tdhock** [comment]
similar to #52 I don't think we should modify the default plot method. instead you should create your own ggplot. all of the data are available in atime.results$measurements. if that is ok then please close this issue.

**Comment by Anirban166** [comment]
> Thanks @Anirban166, my issue was how to get the base, CRAN and head on the graph, as @tdhock expect, for this I have a similar graph.

Anytime, and that's something that came up after this I presume? (cause you only mentioned to me earlier that you wanted help with creating a plot with the time measurements as opposed to having both time and memory, but either way, it seems like you got it done in #52 so I'm glad)

**Comment by Anirban166** [comment]
> Thanks @Anirban166, my issue was how to get the base, CRAN and head on the graph, as @tdhock expect, for this I have a similar graph.

Anytime, and that seperate issue is something that came up after this I presume? (cause you only mentioned to me earlier that you wanted help with creating a plot with the time measurements as opposed to having both time and memory, but either way, it seems like you got it done in #52 so I'm glad)
