### ISSUE TITLE
overhead of running python code from reticulate in R.

### ISSUE THREAD

**Issue by DorisAmoakohene** [tdhock/atime#54]
@tdhock I will want to address this comment, but how to go about the graph is confusing to me 

https://github.com/rdatatable-community/The-Raft/pull/24#issuecomment-2165951806
"it would make your blog post more convincing if you had some discussion of the overhead of running python code from reticulate in R. Is the overhead constant? (should be) Would be great if you could make an atime plot that shows that py_run_string has takes constant time -- how much? 0.01, 0.001 seconds?"

for the first part i have this, to include as the overhead of running python code from reticulate in R.

"The overhead of using the reticulate package in R to run Python code can vary depending on the complexity of the Python code and how frequently R and Python are switching between each other. This overhead is typically constant for small, simple Python scripts, but can become more significant for larger or more complex Python code. 
The code sets up a Python environment using reticulate, creates a virtual environment, and then uses the atime package to benchmark the performance of writing a dataframe to a CSV file using two different methods: data.table::fwrite and pandas::to_csv.
The key factors that influence the overhead in this case are the initialization of the Python environment and the data transfer between R and Python. The data transfer overhead between R and Python is likely to be relatively constant, as the code is simply writing a dataframe to a CSV file, which involves a relatively small amount of data being passed back and forth. The size of the dataframe being processed is also not changing significantly, as the N parameter is being varied in powers of 10 from 100 to 100,000 rows."

**Comment by tdhock** [comment]
what are you quoting that from? reticulate docs? please add link.
you can use atime to figure out how much time `py_run_string` when not copying anything versus copying something that depends on data size N, etc

**Comment by DorisAmoakohene** [comment]
is it okay to show the py_run_string using the reference best like this
![Screenshot 2024-06-26 150315](https://github.com/tdhock/atime/assets/143125519/ee1ffb45-3a38-4091-84a6-16a02588f3df)

**Comment by tdhock** [comment]
yes this is exactly what I had in mind, here you can see that the overhead is less than a millisecond (actually less than 0.0001 seconds)

**Comment by DorisAmoakohene** [comment]
Yes, I can see that too, I will include this plot in my write up.

**Comment by DorisAmoakohene** [comment]
@tdhock, this result has been showed above and added to the write up.
https://github.com/tdhock/atime/issues/54#issuecomment-2192700891
