### ISSUE TITLE
FR: clearer labelling of plot ordering

### ISSUE THREAD

**Issue by MichaelChirico** [tdhock/atime#60]
It took Toby pointing out here for me to realize that the plots are ordered by _p_-value:

https://github.com/Rdatatable/data.table/pull/6485#issuecomment-2336672382

It would be nice to have some overall labelling to the plot, first thing could be a quick sentence like "plots are ordered by _p_-value". This will help the plots be more self-contained.

**Comment by tdhock** [comment]
fixed by https://github.com/tdhock/atime/commit/74d4bc18a5e27900b80fb5e8e79379e96652983f
example viz now has title with # of test cases and info about T-test.
![image](https://github.com/user-attachments/assets/cf6b7dd5-1440-4279-94ff-62d5daf2db81)

**Comment by MichaelChirico** [comment]
Excellent!
