### ISSUE TITLE
quadratic time and memory complexity of write.csv in number of columns

### ISSUE THREAD

**Issue by tdhock** [tdhock/atime#9]
Note: this is not an issue with the atime package, but instead an issue with base R which was revealed by using atime.
I did a systematic comparison of write.csv with similar functions, see below.
![figure-write-real-vary-cols](https://user-images.githubusercontent.com/932850/228733740-1d50ee3d-14dc-4f69-812c-556e4da43501.png)

That is a log-log plot of memory (top panel Y axis) and time(bottom panel Y axis) as a function of number of columns (X axis), so the larger slope of write.csv indicates a larger asymptotic complexity class. When I draw references lines on top, I observe that write.csv is quadratic time and memory (N^2), whereas data.table::fwrite is linear (N), see below.

![figure-write-real-vary-cols-complexity](https://user-images.githubusercontent.com/932850/228733806-64f16f53-0d06-4862-873c-3971b04ab0f8.png)

Can write.csv be improved to use a linear time algorithm, so it can handle CSV files with larger numbers of columns?

source code: https://github.com/tdhock/atime/blob/ec5295859f4a74bc7b137a9eec7c5a29d91c1ded/vignettes/compare-data.table-tidyverse.Rmd
rendered: https://rcdata.nau.edu/genomic-ml/atime/vignettes/compare-data.table-tidyverse.html
```r
sessionInfo()
#> R version 4.2.3 (2023-03-15)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Red Hat Enterprise Linux 8.7 (Ootpa)
#> 
#> Matrix products: default
#> BLAS:   /projects/genomic-ml/lib64/R/lib/libRblas.so
#> LAPACK: /projects/genomic-ml/lib64/R/lib/libRlapack.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#>  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#>  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#>  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#>  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  utils     datasets  grDevices methods   base     
#> 
#> other attached packages:
#> [1] directlabels_2021.2.24 ggplot2_3.4.1          data.table_1.14.8     
#> 
#> loaded via a namespace (and not attached):
#>  [1] highr_0.10       pillar_1.9.0     bslib_0.4.2      compiler_4.2.3  
#>  [5] jquerylib_0.1.4  tools_4.2.3      digest_0.6.31    bit_4.0.5       
#>  [9] gtable_0.3.3     jsonlite_1.8.4   evaluate_0.20    lifecycle_1.0.3 
#> [13] tibble_3.2.1     lattice_0.20-45  pkgconfig_2.0.3  rlang_1.1.0     
#> [17] bench_1.1.2      cli_3.6.1        xfun_0.38        fastmap_1.1.1   
#> [21] withr_2.5.0      dplyr_1.1.1      knitr_1.42       generics_0.1.3  
#> [25] vctrs_0.6.1      sass_0.4.5       hms_1.1.3        bit64_4.0.5     
#> [29] grid_4.2.3       tidyselect_1.2.0 glue_1.6.2       atime_2022.12.14
#> [33] R6_2.5.1         fansi_1.0.4      profmem_0.6.0    vroom_1.6.1     
#> [37] rmarkdown_2.21   purrr_1.0.1      tidyr_1.3.0      farver_2.1.1    
#> [41] readr_2.1.4      tzdb_0.3.0       magrittr_2.0.3   nc_2020.8.6     
#> [45] scales_1.2.1     htmltools_0.5.5  colorspace_2.1-1 quadprog_1.5-8  
#> [49] utf8_1.2.3       munsell_0.5.0    cachem_1.0.7     crayon_1.5.2
```

**Comment by tdhock** [comment]
data.table::fwrite is linear time and memory, and the source code is here https://github.com/Rdatatable/data.table/blob/master/src/fwrite.c (for people trying to improve the other methods, probably useful to see how data.table::fwrite works).

**Comment by tdhock** [comment]
for figures above, input to write.csv was data.table.
@gmbecker wrote on R-devel that write.csv is linear in number of columns if input is matrix.
The figure below confirms that.
![image](https://user-images.githubusercontent.com/932850/229188429-4cd30376-24fe-4f4e-a00b-22a04a4327db.png)

**Comment by tdhock** [comment]
@gmbecker also wrote a patch https://bugs.r-project.org/attachment.cgi?id=3164&action=edit
and claimed https://bugs.r-project.org/show_bug.cgi?id=18500#c0 that it should change the quadratic time to linear time, for the case of a data.frame with columns that are not objects, is.object(x)==FALSE. I applied the patch to R-devel and then re-ran my script, which confirms the patch results in improvement to linear time, see below.
![image](https://user-images.githubusercontent.com/932850/229205386-bfc0e4e1-d6a2-4050-9596-938793609ee7.png)

**Comment by gmbecker** [comment]
@bastistician has applied my patch with a well deserved acknowledgement of your initial report @tdhock

**Comment by gmbecker** [comment]
It does not include factor (The actual check is `is.object(z) && !is.factor(z)`), which is why this patch is "probably sufficient" for the short term.

**Comment by gmbecker** [comment]
My test code is as follows (Sorry for not using `atime` but I didn't want to take the time to learn in 'in flight' so to speak):

```


testfun <- function(nc = 10000, nobjcol = 0, file = tempfile(), min_it = 5) {
    if(length(nc) > 1)
        return(do.call(rbind.data.frame, c(list(deparse.level = 0, make.row.names = FALSE), lapply(nc, testfun, nobjcol = nobjcol, file = file, min_it = min_it))))
    if(length(nobjcol) > 1)
        return(do.call(rbind.data.frame, c(list(deparse.level = 0, make.row.names = FALSE), lapply(nobjcol, function(x) testfun(nc = nc, nobjcol = x, file = file, min_it = min_it)))))

    df <- as.data.frame(matrix(rnorm(nc * 10), nrow = 10))
    if(nobjcol > 0) {
        nobjcol <- min(nobjcol, ncol(df))
        df[seq_len(nobjcol)] <- lapply(df[seq_len(nobjcol)],
                                       function(x) structure(x, class = "hahaha"))
    }


    ret <- bench::mark(write.csv(df, file), min_iterations = 5)
    ret$n_col <- nc
    ret$n_objcol <- nobjcol
    ret[, c("n_col", "n_objcol",  "min", "median", "itr/sec", "mem_alloc", "gc/sec", "n_itr", "total_time")]

}


res <- testfun(seq(5000, 15000, by = 5000), seq(0, 8000, by = 2000))
```
That will give you a tibble with `n_col`, `n_objcol` and the things that `bench::mark` spits out

**Comment by tdhock** [comment]
I confirm that, after applying the patch, writing a data table with POSIXct columns to CSV using write.csv is still quadratic time, see below.
![image](https://user-images.githubusercontent.com/932850/229251356-810d1e27-f842-40fa-afad-a7e05f52c761.png)

**Comment by tdhock** [comment]
Using R-4.3.0 this has been fixed.
![image](https://user-images.githubusercontent.com/932850/234720231-f4bad090-647c-47a3-ae71-6a83f55c7d8c.png)
